### ISSUE TITLE
Remove workflow execution duplication when merging on main

### ISSUE THREAD

**Issue by rodrigo-o** [lambdaclass/lambda_ethereum_rust#1041]
This is due to having both `merge_group` and `push` rules, we need to get rid of the push ones:

```yml
name: CI
on:
  merge_group:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "**/README.md"
      - "**/docs/**"
```

![image](https://github.com/user-attachments/assets/0877c38a-ce4e-41c6-bd37-42c8a272ff45)
