### ISSUE TITLE
LEVM: make operations safe

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/lambda_ethereum_rust#1075]
We are making operations unsafely throughout the codebase, in some cases there are potential overflows. We should go through every operation made and perform them safely. We can do this by using `saturating_op`, `wrapping_op`, etc.

**Extra**: add the following lints to the `crates/vm/levm/Cargo.toml`

```toml
[lints.clippy]
arithmetic_side_effects = "deny"
panicking_overflow_checks = "warn"
manual_saturating_arithmetic = "warn"
```
